### ISSUE TITLE
Поддержка драйверов

### ISSUE THREAD

**Issue by stajor81** [achest/stepperQ#8]
Здравствуйте! Поддержки драйверов ШД нет?

**Comment by achest** [comment]
Каких драйверов? Не понимаю. Он у меня ездит с TB5660 и еще более продвинутым драйвером..

**Comment by stajor81** [comment]
Имел ввиду железные драйвера шаговых двигателей. А4988 например. 
На форуме [http://arduino.ru/forum/programmirovanie/biblioteka-dlya-upravlenie-shagovym-motorom-cherez-preryvanie](url) говорилось, что на тот момент вроде как не было поддержки, но планировалась.

**Comment by achest** [comment]
Должно работать. init(uint8_t dirpin, uint8_t steppin) . Я не помню тестирировал ли актуальную версию с ним, но он он тошибы по сути не отличается. 

Не работает, пиши 2 шт лежит. Только мотор у меня слижком сильный, драйвер переревается... Приходится тошибой гонять. 

На форуме я писал про L298N. С L298N еще не успел простестировать.Там логика совершено другая. Но код внутри. Попробуй, может заработает...

**Comment by stajor81** [comment]
С драйвером А4988 работает

**Comment by achest** [comment]
Спасибо за тест и фидбек.
